name: Run EditorMode and PlayMode Test
on:
  workflow_dispach: {}
  jobs:
    test:
    - name: Run EditorMode and PlayMode Test
      runs-on: ubuntu-latest
      steps:
        - name: Check out my unity project.
          uses: actions/checkout@v2
        - name: Run EditorMode and PlayMode Test
          uses: game-ci/unity-test-runner@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: .
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        unityVersion: 2021.3.2f1
        testMode: All
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
